#!/bin/sh
echo "╭───────────────────────────╮"
echo -e "├🔹Hostname: $(uci get system.@system[0].hostname | tr -d '\0')"
echo -e "├📦Type: $(cat /proc/device-tree/model | tr -d '\0')"
echo -e "├🖥️Arsitekture: $(uname -m)"
echo -e "├🛡️Firmware: $(cat /etc/openwrt_release | grep DISTRIB_DESCRIPTION | cut -d "'" -f 2 | tr -d '\0')"
echo -e "├⚙️Platfom: $(cat /etc/openwrt_release | grep DISTRIB_TARGET | cut -d "'" -f 2 | tr -d '\0')"
echo -e "├🪢Kernel: $(uname -r)"
echo -e "├🗓️Date: $(date +"%d %b %Y | %I:%M %p")"
echo -e "├⏱️Uptime: $(uptime | awk '{print $3,$4}' | sed 's/,.*//')"
echo -e "├🌡️Temperature: $(awk '{printf "%.2f°C\n", $1/1000}' /sys/class/thermal/thermal_zone0/temp)"
echo -e "├💡Load average: $(awk '{printf "%.0f%%", $1 * 100}' /proc/loadavg)"
echo -e "├ ⚡Cpu usage: $(mpstat 1 1 | tail -n 1 | awk '{printf "%.2f%%", 100 - $NF}')"
echo "╰───────────────────────────╯"